language: python
python:
- 3.6
install:
- pip install pipenv==2018.10.9
- pipenv install --skip-lock
- pipenv install --dev --skip-lock

script:
- pytest -p no:warnings --cov=./
after_success:
- codecov
